spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=INBOUND_INSURANCE;encrypt=true;trustServerCertificate=true;
    username: sa
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
